#ifndef LEFTBAGDETECTORPLUGIN_GLOBAL_H
#define LEFTBAGDETECTORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef LEFTBAGDETECTORPLUGIN_LIB
# define LEFTBAGDETECTORPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define LEFTBAGDETECTORPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // LEFTBAGDETECTORPLUGIN_GLOBAL_H
